// Add confirmed members in the desired rank/display order.
// Each entry: { name: "Full name", rank: "Rank", photo: "images/members/filename.webp" }
// Leave photo empty when a portrait is not yet available.
window.membershipData = [
  { name: "Ed Leipply", rank: "Chief", photo: "images/members/ed-leipply.webp" },
  { name: "Josh Crain", rank: "Assistant Chief", photo: "images/members/josh-crain.webp" },
  { name: "William Schoenfeld", rank: "Captain (Operations)", photo: "images/members/william-schoenfeld.webp" },
  { name: "Ray Thomason", rank: "Captain (Training / Certification Coordinator)", photo: "" },
  { name: "Dylan Dearing", rank: "Lieutenant", photo: "images/members/dylan-dearing.webp" },
  { name: "Jeff Caldwell", rank: "Lieutenant", photo: "images/members/jeff-caldwell.webp" },
  { name: "Blayne Caldwell", rank: "Firefighter", photo: "" },
  { name: "Michael Crain", rank: "Firefighter", photo: "" },
  { name: "Austen Dearing", rank: "Firefighter", photo: "images/members/austen-dearing.jpg" },
  { name: "Wesley Dennehy", rank: "Firefighter", photo: "" },
  { name: "Leah Fluitt", rank: "Firefighter", photo: "images/members/leah-fluitt.jpg" },
  { name: "Ty Hardy", rank: "Firefighter", photo: "images/members/ty-hardy.jpg" },
  { name: "Ryan Hill", rank: "Firefighter", photo: "images/members/ryan-hill.jpg" },
  { name: "Patrick Jolly", rank: "Firefighter", photo: "images/members/patrick-jolly.jpg" },
  { name: "Cutter Leipply", rank: "Firefighter", photo: "" },
  { name: "Lorenzo Reyes", rank: "Firefighter", photo: "images/members/lorenzo-reyes.jpg" },
  { name: "Colt Risher", rank: "Firefighter", photo: "" },
  { name: "Cory Roberts", rank: "Firefighter", photo: "" },
  { name: "Monica Schulze", rank: "Firefighter", photo: "" },
  { name: "Ryan Tucker", rank: "Firefighter", photo: "" },
  { name: "Brittany Crain", rank: "Rehab", photo: "images/members/brittany-crain.jpg" },
  { name: "Delany Crain", rank: "Rehab", photo: "" },
  { name: "Yana Hill", rank: "Rehab", photo: "images/members/yana-hill.jpg" },
  { name: "Ashlee Jolly", rank: "Rehab", photo: "images/members/ashlee-jolly.jpg" },
  { name: "Carolyn Leipply", rank: "Rehab", photo: "images/members/carolyn-leipply.jpg" },
  { name: "Tasha Roberts", rank: "Rehab", photo: "" },
  { name: "Tyler Roberts", rank: "Rehab", photo: "" },
];
